// Code generated by ogen, DO NOT EDIT.

package ovt

// ScanURLParams is parameters of scan-url operation.
type ScanURLParams struct {
	// Your API key.
	XApikey string
}

// URLInfoParams is parameters of url-info operation.
type URLInfoParams struct {
	// Your API key.
	XApikey string
	// URL identifier or base64 representation of URL to scan (w/o padding).
	ID string
}

// UrlsAnalyseParams is parameters of urls-analyse operation.
type UrlsAnalyseParams struct {
	// URL identifier.
	ID string
	// Your API key.
	XApikey string
}
