// Code generated by ogen, DO NOT EDIT.

package ovt

// FileInfoParams is parameters of file-info operation.
type FileInfoParams struct {
	// SHA-256, SHA-1 or MD5 identifying the file.
	ID string
	// Your API key.
	XApikey string
}

// URLInfoParams is parameters of url-info operation.
type URLInfoParams struct {
	// Your API key.
	XApikey string
	// URL identifier or base64 representation of URL to scan (w/o padding).
	ID string
}
