// Code generated by ogen, DO NOT EDIT.

package ovt

import (
	"github.com/go-faster/jx"
)

// The VirusTotal API follows the conventional HTTP response codes to indicate success or failure.
// Codes in the `2xx` range indicate success. Codes in the `4xx` range indicate an error in the
// request (e.g. a missing parameter, a resource was not found). Codes in the `5xx` range indicate an
// error in VirusTotal's servers and should be rare.
// Unsuccessful requests return additional information about the error in JSON format.
// Ref: #/components/schemas/Error
type Error struct {
	// * `BadRequestError` (400) - The API request is invalid or malformed. The message usually provides
	// details about why the request is not valid.
	// * `WrongCredentialsError` (401) - The provided API key is incorrect.
	// * `AuthenticationRequiredError` (401) - The operation requires an authenticated user. Verify that
	// you have provided your API key.
	// * `TooManyRequestsError` (429) - Too many requests.
	// * `ForbiddenError` (403) - You are not allowed to perform the requested operation.
	// * `NotFoundError` (404) - The requested resource was not found.
	// * `QuotaExceededError` (429) - You have exceeded one of your quotas (minute, daily or monthly).
	// Daily quotas are reset every day at 00:00 UTC.
	// You may have run out of disk space and/or number of files on your VirusTotal Monitor account.
	// * `UserNotActiveError` (401) - The user account is not active. Make sure you properly activated
	// your account by following the link sent to your email.
	// * `InvalidArgumentError` (400) - Some of the provided arguments are incorrect.
	// * `AlreadyExistsError` (409) - The resource already exists.
	// * `TransientError` (503) - Transient server error.  Retry might work.
	// * `UnselectiveContentQueryError` (400) - Content search query is not selective enough.
	// * `UnsupportedContentQueryError` (400) - Unsupported content search query.
	// * `NotAvailableYet` (400) - The resource is not available yet, but will become available later.
	// * `FailedDependencyError` (424) - The request depended on another request and that request failed.
	// * `DeadlineExceededError` (504) - The operation took too long to complete.
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// GetCode returns the value of Code.
func (s Error) GetCode() ErrorCode {
	return s.Code
}

// GetMessage returns the value of Message.
func (s Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val ErrorCode) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// * `BadRequestError` (400) - The API request is invalid or malformed. The message usually provides
// details about why the request is not valid.
// * `WrongCredentialsError` (401) - The provided API key is incorrect.
// * `AuthenticationRequiredError` (401) - The operation requires an authenticated user. Verify that
// you have provided your API key.
// * `TooManyRequestsError` (429) - Too many requests.
// * `ForbiddenError` (403) - You are not allowed to perform the requested operation.
// * `NotFoundError` (404) - The requested resource was not found.
// * `QuotaExceededError` (429) - You have exceeded one of your quotas (minute, daily or monthly).
// Daily quotas are reset every day at 00:00 UTC.
// You may have run out of disk space and/or number of files on your VirusTotal Monitor account.
// * `UserNotActiveError` (401) - The user account is not active. Make sure you properly activated
// your account by following the link sent to your email.
// * `InvalidArgumentError` (400) - Some of the provided arguments are incorrect.
// * `AlreadyExistsError` (409) - The resource already exists.
// * `TransientError` (503) - Transient server error.  Retry might work.
// * `UnselectiveContentQueryError` (400) - Content search query is not selective enough.
// * `UnsupportedContentQueryError` (400) - Unsupported content search query.
// * `NotAvailableYet` (400) - The resource is not available yet, but will become available later.
// * `FailedDependencyError` (424) - The request depended on another request and that request failed.
// * `DeadlineExceededError` (504) - The operation took too long to complete.
type ErrorCode string

const (
	ErrorCodeBadRequestError              ErrorCode = "BadRequestError"
	ErrorCodeWrongCredentialsError        ErrorCode = "WrongCredentialsError"
	ErrorCodeAuthenticationRequiredError  ErrorCode = "AuthenticationRequiredError"
	ErrorCodeTooManyRequestsError         ErrorCode = "TooManyRequestsError"
	ErrorCodeForbiddenError               ErrorCode = "ForbiddenError"
	ErrorCodeNotFoundError                ErrorCode = "NotFoundError"
	ErrorCodeQuotaExceededError           ErrorCode = "QuotaExceededError"
	ErrorCodeUserNotActiveError           ErrorCode = "UserNotActiveError"
	ErrorCodeInvalidArgumentError         ErrorCode = "InvalidArgumentError"
	ErrorCodeAlreadyExistsError           ErrorCode = "AlreadyExistsError"
	ErrorCodeTransientError               ErrorCode = "TransientError"
	ErrorCodeUnselectiveContentQueryError ErrorCode = "UnselectiveContentQueryError"
	ErrorCodeUnsupportedContentQueryError ErrorCode = "UnsupportedContentQueryError"
	ErrorCodeNotAvailableYet              ErrorCode = "NotAvailableYet"
	ErrorCodeFailedDependencyError        ErrorCode = "FailedDependencyError"
	ErrorCodeDeadlineExceededError        ErrorCode = "DeadlineExceededError"
)

// NewOptInt returns new OptInt with value set to v.
func NewOptInt(v int) OptInt {
	return OptInt{
		Value: v,
		Set:   true,
	}
}

// OptInt is optional int.
type OptInt struct {
	Value int
	Set   bool
}

// IsSet returns true if OptInt was set.
func (o OptInt) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt) Reset() {
	var v int
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt) SetTo(v int) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt) Get() (v int, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt) Or(d int) int {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptScanURLReq returns new OptScanURLReq with value set to v.
func NewOptScanURLReq(v ScanURLReq) OptScanURLReq {
	return OptScanURLReq{
		Value: v,
		Set:   true,
	}
}

// OptScanURLReq is optional ScanURLReq.
type OptScanURLReq struct {
	Value ScanURLReq
	Set   bool
}

// IsSet returns true if OptScanURLReq was set.
func (o OptScanURLReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptScanURLReq) Reset() {
	var v ScanURLReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptScanURLReq) SetTo(v ScanURLReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptScanURLReq) Get() (v ScanURLReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptScanURLReq) Or(d ScanURLReq) ScanURLReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptURLObjectLastAnalysisResultsCategory returns new OptURLObjectLastAnalysisResultsCategory with value set to v.
func NewOptURLObjectLastAnalysisResultsCategory(v URLObjectLastAnalysisResultsCategory) OptURLObjectLastAnalysisResultsCategory {
	return OptURLObjectLastAnalysisResultsCategory{
		Value: v,
		Set:   true,
	}
}

// OptURLObjectLastAnalysisResultsCategory is optional URLObjectLastAnalysisResultsCategory.
type OptURLObjectLastAnalysisResultsCategory struct {
	Value URLObjectLastAnalysisResultsCategory
	Set   bool
}

// IsSet returns true if OptURLObjectLastAnalysisResultsCategory was set.
func (o OptURLObjectLastAnalysisResultsCategory) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptURLObjectLastAnalysisResultsCategory) Reset() {
	var v URLObjectLastAnalysisResultsCategory
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptURLObjectLastAnalysisResultsCategory) SetTo(v URLObjectLastAnalysisResultsCategory) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptURLObjectLastAnalysisResultsCategory) Get() (v URLObjectLastAnalysisResultsCategory, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptURLObjectLastAnalysisResultsCategory) Or(d URLObjectLastAnalysisResultsCategory) URLObjectLastAnalysisResultsCategory {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

type ScanURLBadRequest struct {
	Error Error `json:"error"`
}

// GetError returns the value of Error.
func (s ScanURLBadRequest) GetError() Error {
	return s.Error
}

// SetError sets the value of Error.
func (s *ScanURLBadRequest) SetError(val Error) {
	s.Error = val
}

func (*ScanURLBadRequest) scanURLRes() {}

type ScanURLOK struct {
	Data URLObject `json:"data"`
}

// GetData returns the value of Data.
func (s ScanURLOK) GetData() URLObject {
	return s.Data
}

// SetData sets the value of Data.
func (s *ScanURLOK) SetData(val URLObject) {
	s.Data = val
}

func (*ScanURLOK) scanURLRes() {}

type ScanURLReq struct {
	// URL to scan.
	URL string `json:"url"`
}

// GetURL returns the value of URL.
func (s ScanURLReq) GetURL() string {
	return s.URL
}

// SetURL sets the value of URL.
func (s *ScanURLReq) SetURL(val string) {
	s.URL = val
}

type Sec0 struct {
	APIKey string
}

// GetAPIKey returns the value of APIKey.
func (s Sec0) GetAPIKey() string {
	return s.APIKey
}

// SetAPIKey sets the value of APIKey.
func (s *Sec0) SetAPIKey(val string) {
	s.APIKey = val
}

type URLInfoBadRequest struct {
	Error Error `json:"error"`
}

// GetError returns the value of Error.
func (s URLInfoBadRequest) GetError() Error {
	return s.Error
}

// SetError sets the value of Error.
func (s *URLInfoBadRequest) SetError(val Error) {
	s.Error = val
}

func (*URLInfoBadRequest) uRLInfoRes() {}

type URLInfoOK struct {
	Data URLObject `json:"data"`
}

// GetData returns the value of Data.
func (s URLInfoOK) GetData() URLObject {
	return s.Data
}

// SetData sets the value of Data.
func (s *URLInfoOK) SetData(val URLObject) {
	s.Data = val
}

func (*URLInfoOK) uRLInfoRes() {}

// URLs doesn't only represent information by themselves, but also can give
// contextual information about files and other elements on VT.
// Different URL calls may return different URL-related objects that we list here.
// Ref: #/components/schemas/URLObject
type URLObject struct {
	// They key is the partner who categorised the URL and the value is the URL's category according to
	// that partner.
	Categories URLObjectCategories `json:"categories"`
	// Dictionary including difference hash and md5 hash of the URL's favicon. Only returned in premium
	// API.
	Favicon URLObjectFavicon `json:"favicon"`
	// UTC timestamp of the date where the URL was first submitted to VirusTotal.
	FirstSubmissionDate int `json:"first_submission_date"`
	// Containing all meta tags (only for URLs downloading a HTML). Keys are the meta tag name and value
	// is a list containing all values of that meta tag.
	HTMLMeta URLObjectHTMLMeta `json:"html_meta"`
	// UTC timestamp representing last time the URL was scanned.
	LastAnalysisDate int `json:"last_analysis_date"`
	// Result from URL scanners. dict with scanner name as key and a dict with notes/result from that
	// scanner as value.
	LastAnalysisResults URLObjectLastAnalysisResults `json:"last_analysis_results"`
	// Number of different results from this scans.
	LastAnalysisStats URLObjectLastAnalysisStats `json:"last_analysis_stats"`
	// If the original URL redirects, where does it end.
	LastFinalURL string `json:"last_final_url"`
	// HTTP response code of the last response.
	LastHTTPResponseCode int `json:"last_http_response_code"`
	// Length in bytes of the content received.
	LastHTTPResponseContentLength int `json:"last_http_response_content_length"`
	// URL response body's SHA256 hash.
	LastHTTPResponseContentSHA256 string `json:"last_http_response_content_sha256"`
	// Containing the website's cookies.
	LastHTTPResponseCookies URLObjectLastHTTPResponseCookies `json:"last_http_response_cookies"`
	// Containing headers and values of last HTTP response.
	LastHTTPResponseHeaders URLObjectLastHTTPResponseHeaders `json:"last_http_response_headers"`
	// UTC timestamp representing last modification date.
	LastModificationDate int `json:"last_modification_date"`
	// UTC timestamp representing last time it was sent to be analysed.
	LastSubmissionDate int `json:"last_submission_date"`
	// Containing links to different domains.
	OutgoingLinks []string `json:"outgoing_links"`
	// History of redirections followed when visiting a given URL. The last URL of the chain is not
	// included in the list since it is available at the `last_final_url` attribute.
	RedirectionChain []string `json:"redirection_chain"`
	// Value of votes from VT community.
	Reputation int `json:"reputation"`
	// Tags.
	Tags []string `json:"tags"`
	// Targeted brand info extracted from phishing engines.
	TargetedBrand URLObjectTargetedBrand `json:"targeted_brand"`
	// Number of times that URL has been checked.
	TimesSubmitted int `json:"times_submitted"`
	// Webpage title.
	Title string `json:"title"`
	// Containing the number of positive ("harmless") and negative ("malicious") votes received from VT
	// community.
	TotalVotes URLObjectTotalVotes `json:"total_votes"`
	// Contains all found trackers in that URL in a historical manner. Every key is a tracker name, which
	// is a dictionary containing:.
	Trackers URLObjectTrackers `json:"trackers"`
	// Original URL to be scanned.
	URL string `json:"url"`
}

// GetCategories returns the value of Categories.
func (s URLObject) GetCategories() URLObjectCategories {
	return s.Categories
}

// GetFavicon returns the value of Favicon.
func (s URLObject) GetFavicon() URLObjectFavicon {
	return s.Favicon
}

// GetFirstSubmissionDate returns the value of FirstSubmissionDate.
func (s URLObject) GetFirstSubmissionDate() int {
	return s.FirstSubmissionDate
}

// GetHTMLMeta returns the value of HTMLMeta.
func (s URLObject) GetHTMLMeta() URLObjectHTMLMeta {
	return s.HTMLMeta
}

// GetLastAnalysisDate returns the value of LastAnalysisDate.
func (s URLObject) GetLastAnalysisDate() int {
	return s.LastAnalysisDate
}

// GetLastAnalysisResults returns the value of LastAnalysisResults.
func (s URLObject) GetLastAnalysisResults() URLObjectLastAnalysisResults {
	return s.LastAnalysisResults
}

// GetLastAnalysisStats returns the value of LastAnalysisStats.
func (s URLObject) GetLastAnalysisStats() URLObjectLastAnalysisStats {
	return s.LastAnalysisStats
}

// GetLastFinalURL returns the value of LastFinalURL.
func (s URLObject) GetLastFinalURL() string {
	return s.LastFinalURL
}

// GetLastHTTPResponseCode returns the value of LastHTTPResponseCode.
func (s URLObject) GetLastHTTPResponseCode() int {
	return s.LastHTTPResponseCode
}

// GetLastHTTPResponseContentLength returns the value of LastHTTPResponseContentLength.
func (s URLObject) GetLastHTTPResponseContentLength() int {
	return s.LastHTTPResponseContentLength
}

// GetLastHTTPResponseContentSHA256 returns the value of LastHTTPResponseContentSHA256.
func (s URLObject) GetLastHTTPResponseContentSHA256() string {
	return s.LastHTTPResponseContentSHA256
}

// GetLastHTTPResponseCookies returns the value of LastHTTPResponseCookies.
func (s URLObject) GetLastHTTPResponseCookies() URLObjectLastHTTPResponseCookies {
	return s.LastHTTPResponseCookies
}

// GetLastHTTPResponseHeaders returns the value of LastHTTPResponseHeaders.
func (s URLObject) GetLastHTTPResponseHeaders() URLObjectLastHTTPResponseHeaders {
	return s.LastHTTPResponseHeaders
}

// GetLastModificationDate returns the value of LastModificationDate.
func (s URLObject) GetLastModificationDate() int {
	return s.LastModificationDate
}

// GetLastSubmissionDate returns the value of LastSubmissionDate.
func (s URLObject) GetLastSubmissionDate() int {
	return s.LastSubmissionDate
}

// GetOutgoingLinks returns the value of OutgoingLinks.
func (s URLObject) GetOutgoingLinks() []string {
	return s.OutgoingLinks
}

// GetRedirectionChain returns the value of RedirectionChain.
func (s URLObject) GetRedirectionChain() []string {
	return s.RedirectionChain
}

// GetReputation returns the value of Reputation.
func (s URLObject) GetReputation() int {
	return s.Reputation
}

// GetTags returns the value of Tags.
func (s URLObject) GetTags() []string {
	return s.Tags
}

// GetTargetedBrand returns the value of TargetedBrand.
func (s URLObject) GetTargetedBrand() URLObjectTargetedBrand {
	return s.TargetedBrand
}

// GetTimesSubmitted returns the value of TimesSubmitted.
func (s URLObject) GetTimesSubmitted() int {
	return s.TimesSubmitted
}

// GetTitle returns the value of Title.
func (s URLObject) GetTitle() string {
	return s.Title
}

// GetTotalVotes returns the value of TotalVotes.
func (s URLObject) GetTotalVotes() URLObjectTotalVotes {
	return s.TotalVotes
}

// GetTrackers returns the value of Trackers.
func (s URLObject) GetTrackers() URLObjectTrackers {
	return s.Trackers
}

// GetURL returns the value of URL.
func (s URLObject) GetURL() string {
	return s.URL
}

// SetCategories sets the value of Categories.
func (s *URLObject) SetCategories(val URLObjectCategories) {
	s.Categories = val
}

// SetFavicon sets the value of Favicon.
func (s *URLObject) SetFavicon(val URLObjectFavicon) {
	s.Favicon = val
}

// SetFirstSubmissionDate sets the value of FirstSubmissionDate.
func (s *URLObject) SetFirstSubmissionDate(val int) {
	s.FirstSubmissionDate = val
}

// SetHTMLMeta sets the value of HTMLMeta.
func (s *URLObject) SetHTMLMeta(val URLObjectHTMLMeta) {
	s.HTMLMeta = val
}

// SetLastAnalysisDate sets the value of LastAnalysisDate.
func (s *URLObject) SetLastAnalysisDate(val int) {
	s.LastAnalysisDate = val
}

// SetLastAnalysisResults sets the value of LastAnalysisResults.
func (s *URLObject) SetLastAnalysisResults(val URLObjectLastAnalysisResults) {
	s.LastAnalysisResults = val
}

// SetLastAnalysisStats sets the value of LastAnalysisStats.
func (s *URLObject) SetLastAnalysisStats(val URLObjectLastAnalysisStats) {
	s.LastAnalysisStats = val
}

// SetLastFinalURL sets the value of LastFinalURL.
func (s *URLObject) SetLastFinalURL(val string) {
	s.LastFinalURL = val
}

// SetLastHTTPResponseCode sets the value of LastHTTPResponseCode.
func (s *URLObject) SetLastHTTPResponseCode(val int) {
	s.LastHTTPResponseCode = val
}

// SetLastHTTPResponseContentLength sets the value of LastHTTPResponseContentLength.
func (s *URLObject) SetLastHTTPResponseContentLength(val int) {
	s.LastHTTPResponseContentLength = val
}

// SetLastHTTPResponseContentSHA256 sets the value of LastHTTPResponseContentSHA256.
func (s *URLObject) SetLastHTTPResponseContentSHA256(val string) {
	s.LastHTTPResponseContentSHA256 = val
}

// SetLastHTTPResponseCookies sets the value of LastHTTPResponseCookies.
func (s *URLObject) SetLastHTTPResponseCookies(val URLObjectLastHTTPResponseCookies) {
	s.LastHTTPResponseCookies = val
}

// SetLastHTTPResponseHeaders sets the value of LastHTTPResponseHeaders.
func (s *URLObject) SetLastHTTPResponseHeaders(val URLObjectLastHTTPResponseHeaders) {
	s.LastHTTPResponseHeaders = val
}

// SetLastModificationDate sets the value of LastModificationDate.
func (s *URLObject) SetLastModificationDate(val int) {
	s.LastModificationDate = val
}

// SetLastSubmissionDate sets the value of LastSubmissionDate.
func (s *URLObject) SetLastSubmissionDate(val int) {
	s.LastSubmissionDate = val
}

// SetOutgoingLinks sets the value of OutgoingLinks.
func (s *URLObject) SetOutgoingLinks(val []string) {
	s.OutgoingLinks = val
}

// SetRedirectionChain sets the value of RedirectionChain.
func (s *URLObject) SetRedirectionChain(val []string) {
	s.RedirectionChain = val
}

// SetReputation sets the value of Reputation.
func (s *URLObject) SetReputation(val int) {
	s.Reputation = val
}

// SetTags sets the value of Tags.
func (s *URLObject) SetTags(val []string) {
	s.Tags = val
}

// SetTargetedBrand sets the value of TargetedBrand.
func (s *URLObject) SetTargetedBrand(val URLObjectTargetedBrand) {
	s.TargetedBrand = val
}

// SetTimesSubmitted sets the value of TimesSubmitted.
func (s *URLObject) SetTimesSubmitted(val int) {
	s.TimesSubmitted = val
}

// SetTitle sets the value of Title.
func (s *URLObject) SetTitle(val string) {
	s.Title = val
}

// SetTotalVotes sets the value of TotalVotes.
func (s *URLObject) SetTotalVotes(val URLObjectTotalVotes) {
	s.TotalVotes = val
}

// SetTrackers sets the value of Trackers.
func (s *URLObject) SetTrackers(val URLObjectTrackers) {
	s.Trackers = val
}

// SetURL sets the value of URL.
func (s *URLObject) SetURL(val string) {
	s.URL = val
}

// They key is the partner who categorised the URL and the value is the URL's category according to
// that partner.
type URLObjectCategories map[string]jx.Raw

func (s *URLObjectCategories) init() URLObjectCategories {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Dictionary including difference hash and md5 hash of the URL's favicon. Only returned in premium
// API.
type URLObjectFavicon struct {
	// Difference hash.
	Dhash OptString `json:"dhash"`
	// Favicon's MD5 hash.
	RawMD5 OptString `json:"raw_md5"`
}

// GetDhash returns the value of Dhash.
func (s URLObjectFavicon) GetDhash() OptString {
	return s.Dhash
}

// GetRawMD5 returns the value of RawMD5.
func (s URLObjectFavicon) GetRawMD5() OptString {
	return s.RawMD5
}

// SetDhash sets the value of Dhash.
func (s *URLObjectFavicon) SetDhash(val OptString) {
	s.Dhash = val
}

// SetRawMD5 sets the value of RawMD5.
func (s *URLObjectFavicon) SetRawMD5(val OptString) {
	s.RawMD5 = val
}

// Containing all meta tags (only for URLs downloading a HTML). Keys are the meta tag name and value
// is a list containing all values of that meta tag.
type URLObjectHTMLMeta map[string]jx.Raw

func (s *URLObjectHTMLMeta) init() URLObjectHTMLMeta {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Result from URL scanners. dict with scanner name as key and a dict with notes/result from that
// scanner as value.
type URLObjectLastAnalysisResults struct {
	// Normalized result. can be:
	// * `harmless` - (site is not malicious),
	// * `undetected` - (scanner has no opinion about this site),
	// * `suspicious` - (scanner thinks the site is suspicious),
	// * `malicious` - (scanner thinks the site is malicious).
	Category OptURLObjectLastAnalysisResultsCategory `json:"category"`
	// Complete name of the URL scanning service.
	EngineName OptString `json:"engine_name"`
	// Type of service given by that URL scanning service (i.e. "blacklist").
	Method OptString `json:"method"`
	// Raw value returned by the URL scanner ("clean", "malicious", "suspicious", "phishing"). It may
	// vary from scanner to scanner, hence the need for the "category" field for normalisation.
	Result OptString `json:"result"`
}

// GetCategory returns the value of Category.
func (s URLObjectLastAnalysisResults) GetCategory() OptURLObjectLastAnalysisResultsCategory {
	return s.Category
}

// GetEngineName returns the value of EngineName.
func (s URLObjectLastAnalysisResults) GetEngineName() OptString {
	return s.EngineName
}

// GetMethod returns the value of Method.
func (s URLObjectLastAnalysisResults) GetMethod() OptString {
	return s.Method
}

// GetResult returns the value of Result.
func (s URLObjectLastAnalysisResults) GetResult() OptString {
	return s.Result
}

// SetCategory sets the value of Category.
func (s *URLObjectLastAnalysisResults) SetCategory(val OptURLObjectLastAnalysisResultsCategory) {
	s.Category = val
}

// SetEngineName sets the value of EngineName.
func (s *URLObjectLastAnalysisResults) SetEngineName(val OptString) {
	s.EngineName = val
}

// SetMethod sets the value of Method.
func (s *URLObjectLastAnalysisResults) SetMethod(val OptString) {
	s.Method = val
}

// SetResult sets the value of Result.
func (s *URLObjectLastAnalysisResults) SetResult(val OptString) {
	s.Result = val
}

// Normalized result. can be:
// * `harmless` - (site is not malicious),
// * `undetected` - (scanner has no opinion about this site),
// * `suspicious` - (scanner thinks the site is suspicious),
// * `malicious` - (scanner thinks the site is malicious).
type URLObjectLastAnalysisResultsCategory string

const (
	URLObjectLastAnalysisResultsCategoryHarmless   URLObjectLastAnalysisResultsCategory = "harmless"
	URLObjectLastAnalysisResultsCategoryUndetected URLObjectLastAnalysisResultsCategory = "undetected"
	URLObjectLastAnalysisResultsCategorySuspicious URLObjectLastAnalysisResultsCategory = "suspicious"
	URLObjectLastAnalysisResultsCategoryMalicious  URLObjectLastAnalysisResultsCategory = "malicious"
)

// Number of different results from this scans.
type URLObjectLastAnalysisStats struct {
	// Number of reports saying that is harmless.
	Harmless OptInt `json:"harmless"`
	// Number of reports saying that is malicious.
	Malicious OptInt `json:"malicious"`
	// Number of reports saying that is suspicious.
	Suspicious OptInt `json:"suspicious"`
	// Number of timeouts when checking this URL.
	Timeout OptInt `json:"timeout"`
	// Number of reports saying that is undetected.
	Undetected OptInt `json:"undetected"`
}

// GetHarmless returns the value of Harmless.
func (s URLObjectLastAnalysisStats) GetHarmless() OptInt {
	return s.Harmless
}

// GetMalicious returns the value of Malicious.
func (s URLObjectLastAnalysisStats) GetMalicious() OptInt {
	return s.Malicious
}

// GetSuspicious returns the value of Suspicious.
func (s URLObjectLastAnalysisStats) GetSuspicious() OptInt {
	return s.Suspicious
}

// GetTimeout returns the value of Timeout.
func (s URLObjectLastAnalysisStats) GetTimeout() OptInt {
	return s.Timeout
}

// GetUndetected returns the value of Undetected.
func (s URLObjectLastAnalysisStats) GetUndetected() OptInt {
	return s.Undetected
}

// SetHarmless sets the value of Harmless.
func (s *URLObjectLastAnalysisStats) SetHarmless(val OptInt) {
	s.Harmless = val
}

// SetMalicious sets the value of Malicious.
func (s *URLObjectLastAnalysisStats) SetMalicious(val OptInt) {
	s.Malicious = val
}

// SetSuspicious sets the value of Suspicious.
func (s *URLObjectLastAnalysisStats) SetSuspicious(val OptInt) {
	s.Suspicious = val
}

// SetTimeout sets the value of Timeout.
func (s *URLObjectLastAnalysisStats) SetTimeout(val OptInt) {
	s.Timeout = val
}

// SetUndetected sets the value of Undetected.
func (s *URLObjectLastAnalysisStats) SetUndetected(val OptInt) {
	s.Undetected = val
}

// Containing the website's cookies.
type URLObjectLastHTTPResponseCookies map[string]jx.Raw

func (s *URLObjectLastHTTPResponseCookies) init() URLObjectLastHTTPResponseCookies {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Containing headers and values of last HTTP response.
type URLObjectLastHTTPResponseHeaders map[string]jx.Raw

func (s *URLObjectLastHTTPResponseHeaders) init() URLObjectLastHTTPResponseHeaders {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Targeted brand info extracted from phishing engines.
type URLObjectTargetedBrand map[string]jx.Raw

func (s *URLObjectTargetedBrand) init() URLObjectTargetedBrand {
	m := *s
	if m == nil {
		m = map[string]jx.Raw{}
		*s = m
	}
	return m
}

// Containing the number of positive ("harmless") and negative ("malicious") votes received from VT
// community.
type URLObjectTotalVotes struct {
	// Number of positive votes.
	Harmless OptInt `json:"harmless"`
	// Number of negative votes.
	Malicious OptInt `json:"malicious"`
}

// GetHarmless returns the value of Harmless.
func (s URLObjectTotalVotes) GetHarmless() OptInt {
	return s.Harmless
}

// GetMalicious returns the value of Malicious.
func (s URLObjectTotalVotes) GetMalicious() OptInt {
	return s.Malicious
}

// SetHarmless sets the value of Harmless.
func (s *URLObjectTotalVotes) SetHarmless(val OptInt) {
	s.Harmless = val
}

// SetMalicious sets the value of Malicious.
func (s *URLObjectTotalVotes) SetMalicious(val OptInt) {
	s.Malicious = val
}

// Contains all found trackers in that URL in a historical manner. Every key is a tracker name, which
// is a dictionary containing:.
type URLObjectTrackers struct {
	// Tracker ID, if available.
	ID OptString `json:"id"`
	// Tracker ingestion date as UNIX timestamp.
	Timestamp OptInt `json:"timestamp"`
	// Tracker script URL.
	URL OptString `json:"url"`
}

// GetID returns the value of ID.
func (s URLObjectTrackers) GetID() OptString {
	return s.ID
}

// GetTimestamp returns the value of Timestamp.
func (s URLObjectTrackers) GetTimestamp() OptInt {
	return s.Timestamp
}

// GetURL returns the value of URL.
func (s URLObjectTrackers) GetURL() OptString {
	return s.URL
}

// SetID sets the value of ID.
func (s *URLObjectTrackers) SetID(val OptString) {
	s.ID = val
}

// SetTimestamp sets the value of Timestamp.
func (s *URLObjectTrackers) SetTimestamp(val OptInt) {
	s.Timestamp = val
}

// SetURL sets the value of URL.
func (s *URLObjectTrackers) SetURL(val OptString) {
	s.URL = val
}

type UrlsAnalyseBadRequest struct {
	Error Error `json:"error"`
}

// GetError returns the value of Error.
func (s UrlsAnalyseBadRequest) GetError() Error {
	return s.Error
}

// SetError sets the value of Error.
func (s *UrlsAnalyseBadRequest) SetError(val Error) {
	s.Error = val
}

func (*UrlsAnalyseBadRequest) urlsAnalyseRes() {}

type UrlsAnalyseOK struct {
	Data URLObject `json:"data"`
}

// GetData returns the value of Data.
func (s UrlsAnalyseOK) GetData() URLObject {
	return s.Data
}

// SetData sets the value of Data.
func (s *UrlsAnalyseOK) SetData(val URLObject) {
	s.Data = val
}

func (*UrlsAnalyseOK) urlsAnalyseRes() {}
